CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID varchar(250) NOT NULL,
  USER_NAME VARCHAR(50) NOT Null,
  PASSWORD VARCHAR(250) NOT NULL,
  PHONE_NO VARCHAR(13) NULL,
  EMAIL varchar(50) Null,
  BIRTH_DATE varchar(10) null,
  AGE INT NULL
);